spring.application.name=order-processing

server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d6lvoevafjfc738prf70-a.oregon-postgres.render.com:5432/orderprocessingdb_719k
spring.datasource.username=orderprocessingdb_719k_user
spring.datasource.password=kcUInPVx5GthTx2MjtNTERC1ds5Feg19
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:schema.sql

# SQL / Hibernate logging for debugging N+1
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=DEBUG

management.endpoints.web.exposure.include=health,info,metrics,prometheus